<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8" %>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>
<%@ taglib uri="/WEB-INF/tld/rmapTagLibrary.tld" prefix="my"  %>
<%@ taglib uri="http://java.sun.com/jsp/jstl/functions" prefix="fn" %>
<%@ taglib uri="http://www.springframework.org/tags/form" prefix="form" %>
<c:set var="pageTitle" value="Settings | RMap Project"/>
<c:set var="currPage" value="home"/>
<%@include file="/includes/headstart.inc" %>  
</head>
<body>
<%@include file="/includes/bodystart.inc" %> 
 
<article class="eleven columns main-content">
	<h1>Settings</h1>
	
	<br/>
	<form:form method="POST" modelAttribute="userSettings">
		<c:if test="${notice!=null}">
			<p class="notice">
				${notice}
			</p>
		</c:if>
		<fieldset>
		<form:hidden path="userId"/>
		
		<legend>User details</legend>
		<form:label path="name">Name *</form:label> 
		<form:errors path="name" cssClass="validationErrors"/>
		<form:input path="name"/>
			
		<form:label path="email">Email *</form:label> 
		<form:errors path="email" cssClass="validationErrors"/>
		<form:input path="email"/>

		<br/>
						
		<c:if test="${not user.hasRMapAgent()}">
			<form:label path="doRMapAgentSync">Generate RMap:Agent</form:label>
			<form:radiobutton path="doRMapAgentSync" value="yes"/> Yes <br/>
			<form:radiobutton path="doRMapAgentSync" value="no"/> No
			<br/><br/>
			<em>An RMap:Agent is required for writing to the public RMap repository. 
			If "Yes" is selected, the following RMap:Agent will be copied to the PUBLIC RMap database 
			<strong>when you create your first DiSCO</strong> and will be associated with your content. This Agent cannot be deleted.</em>
			<br/><br/>
			<p class="greybox">
				<c:if test="${not user.hasRMapAgent()}">
					&lt;autogeneratedId&gt;<br/>
				</c:if>
				<c:if test="${user.authKeyUri.length()>50}">
					<c:set var="authkey" value="${fn:substring(user.authKeyUri, 0, 50)}..."/>
				</c:if>
				<c:if test="${user.authKeyUri.length()<50}">
					<c:set var="authkey" value="${user.authKeyUri}"/>
				</c:if>
				&nbsp;&nbsp;&nbsp;&nbsp;rdf:type &lt;rmap:Agent&gt;<br/>
				&nbsp;&nbsp;&nbsp;&nbsp;foaf:name "${user.name}"<br/>
				&nbsp;&nbsp;&nbsp;&nbsp;rmap:identityProvider &lt;${account.getProviderUrl()}&gt;<br/>
				&nbsp;&nbsp;&nbsp;&nbsp;rmap:userAuthId &lt;${authkey}&gt;<br/>
			</p>	
		</c:if>
			
		<c:if test="${user.hasRMapAgent()}">
			<form:label path="doRMapAgentSync">Synchronize RMap:Agent</form:label>
			<form:radiobutton path="doRMapAgentSync" value="yes"/> Yes <br/>
			<form:radiobutton path="doRMapAgentSync" value="no"/> No
			<br/><br/>
			<em>If "Yes" is selected, updates to the User record will be applied to the public RMap database.
			To disable future updates, please select "No".</em>
			<br/>
		</c:if>
		</fieldset>	
		<div id="formButtons">
			<a href="<c:url value='/user/welcome'/>">Cancel</a>&nbsp;&nbsp;
			<input type="submit" value="Save Changes"/>
		</div>	
		
	</form:form>

</article>

<!-- End main Content --> 
<aside class="five columns right-sidebar">
    <div class="sidebar-widget">
		<h1>&nbsp;</h1>
		<br/>
    	<div class="boxedsidebar">
			<h3>Your Agent ID is</h3><br/>
			<c:if test="${user.hasRMapAgent()}">
				<h3><a href="<c:url value='/agents/${my:httpEncode(user.rmapAgentUri)}'/>">&lt;${user.rmapAgentUri}&gt;</a></h3>
			</c:if>
			<c:if test="${not user.hasRMapAgent()}">
				<h3>&lt;none created&gt;</h3><br/>
				<em>Enable Generate RMap:Agent option to create automatically</em>
			</c:if>
		</div>
	</div>
	<br/>
	<!-- 
	<div class="sidebar-widget">
    	<div class="boxedsidebar">
			<h3>Your Agent's DiSCO ID is</h3><br/>
			<c:if test="${user.hasRMapDiSCO()}">
				<a href="<c:url value='/discos/${my:httpEncode(user.rmapDiSCOUri)}'/>">&lt;${user.rmapDiSCOUri}&gt;</a><br/><br/>
				<em>(<a href="<c:url value='/user/disco'/>" >Update your DiSCO</a>)</em>
			</c:if>
			<c:if test="${not user.hasRMapDiSCO()}">
				<h3>&lt;none created&gt;</h3><br/>
				<em><a href="<c:url value='/user/disco'/>">Create a DiSCO</a> to add details about your Agent</em>
			</c:if>
		</div>
	</div> 
	-->
	
</aside>
<!-- End Right Sidebar -->

<%@include file="/includes/footer.inc" %>