<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="my"  uri="/WEB-INF/tld/rmapTagLibrary.tld" %>
<%@ taglib prefix="fn" uri="http://java.sun.com/jsp/jstl/functions" %>
<%@ taglib prefix="form" uri="http://www.springframework.org/tags/form"  %>
<%@ taglib prefix="tl" tagdir="/WEB-INF/tags" %>

<tl:pageStartStandard user="${user}" pageTitle="Settings"/>

	<c:set var="isAdmin" value="${sessionScope.adminLoggedIn==null ? false : sessionScope.adminLoggedIn}"/>
        
	<article class="eleven columns main-content">
		<h1>Settings
		<c:if test="${isAdmin && userSettings.getName().length()>0}">
			for "${userSettings.getName()}"
		</c:if>
		</h1>
		<c:if test="${isAdmin}">
			<p><a href="<c:url value='/admin/users'/>">Return to Users list</a></p>
		</c:if>
		<br/>
		<form:form method="POST" modelAttribute="userSettings">
			<c:if test="${notice!=null}">
				<p class="notice">
					${notice}
				</p>
			</c:if>
			<fieldset>
			<form:hidden path="userId"/>
			
			<legend>User details</legend>
			<form:label path="name">Name *</form:label> 
			<form:errors path="name" cssClass="validationErrors"/>
			<form:input path="name"/>
				
			<form:label path="email">Email *</form:label> 
			<form:errors path="email" cssClass="validationErrors"/>
			<form:input path="email"/>
					
			<c:if test="${isAdmin}">				
				<form:label path="isActive">User enabled?</form:label>
				<form:radiobutton path="isActive" value="yes"/> Yes<br/>
				<form:radiobutton path="isActive" value="no"/> No (disables user account)
			</c:if>
						
			<c:if test="${!isAdmin}">				
				<form:hidden path="isActive"/>
			</c:if>
						
			<c:if test="${not userSettings.hasRMapAgent()}">
				<form:label path="doRMapAgentSync">Generate RMap:Agent</form:label>
				<form:radiobutton path="doRMapAgentSync" value="yes"/> Yes <br/>
				<form:radiobutton path="doRMapAgentSync" value="no"/> No
				<br/><br/>
				<em>An RMap:Agent is required for writing to the public RMap repository. 
				If "Yes" is selected, the following RMap:Agent will be copied to the PUBLIC RMap database 
				<strong>the first time a DiSCO is created using this account</strong> and will be associated with this account's content. This Agent cannot be deleted.</em>
				<br/><br/>
				<p class="greybox">
					<c:if test="${not userSettings.hasRMapAgent()}">
						&lt;autogeneratedId&gt;<br/>
					</c:if>
					<c:set var="authkey" value="${my:ellipsize(userSettings.authKeyUri, 50)}"/>
					&nbsp;&nbsp;&nbsp;&nbsp;rdf:type &lt;rmap:Agent&gt;<br/>
					&nbsp;&nbsp;&nbsp;&nbsp;foaf:name "${userSettings.name}"<br/>
					&nbsp;&nbsp;&nbsp;&nbsp;rmap:identityProvider &lt;${account==null ? "https://rmap-hub.org" : account.getProviderUrl()}&gt;<br/>
					&nbsp;&nbsp;&nbsp;&nbsp;rmap:userAuthId &lt;${authkey}&gt;<br/>
				</p>	
			</c:if>
			
			<c:if test="${userSettings.hasRMapAgent()}">
				<form:label path="doRMapAgentSync">Synchronize RMap:Agent</form:label>
				<form:radiobutton path="doRMapAgentSync" value="yes"/> Yes <br/>
				<form:radiobutton path="doRMapAgentSync" value="no"/> No
				<br/><br/>
				<em>If "Yes" is selected, updates to the User record will be applied to the public RMap database.
				To disable future updates, please select "No".</em>
				<br/>
			</c:if>
			
			</fieldset>	
			<div id="formButtons">
				<a href="<c:url value='${isAdmin ? \"/admin/users\" : \"/user/welcome\" }'/>">Cancel</a>&nbsp;&nbsp;
				<input type="submit" value="Save Changes"/>
			</div>	
			
		</form:form>
	
	</article>
	
	<!-- End main Content --> 
	<aside class="five columns right-sidebar">
	    <div class="sidebar-widget">
			<h1>&nbsp;</h1>
			<br/>
	    	<div class="boxedsidebar">
				<h3>Your Agent ID is</h3><br/>
				<c:if test="${userSettings.hasRMapAgent()}">
					<h3><a href="<c:url value='/agents/${my:httpEncodeStr(userSettings.getRmapAgentUri())}'/>">&lt;${userSettings.rmapAgentUri}&gt;</a></h3>
				</c:if>
				<c:if test="${not userSettings.hasRMapAgent()}">
					<h3>&lt;none created&gt;</h3><br/>
					<em>Enable Generate RMap:Agent option to create automatically</em>
				</c:if>
			</div>
		</div>
		<br/>
	</aside>
	<!-- End Right Sidebar -->
<tl:pageEndStandard/>