<!DOCTYPE html>
<!--[if lt IE 7 ]><html class="ie ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]><html class="ie ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]><html class="ie ie8" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--><html lang="en"> <!--<![endif]-->
<head>
	<!-- Basic Page Needs
  	================================================== -->
	<meta charset="utf-8">
	<title>${pageTitle}</title>
	<meta name="description" content="">
	<meta name="author" content="">

	<!-- Mobile Specific Metas
  	================================================== -->
	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

	<!-- CSS
  	================================================== -->
	<link rel="stylesheet" href="<c:url value='/includes/stylesheets/base.css'/>">
	<link rel="stylesheet" href="<c:url value='/includes/stylesheets/skeleton.css'/>">
	<link rel="stylesheet" href="<c:url value='/includes/stylesheets/layout.css'/>">
	
	<!--non-local link <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">-->
	<link rel="stylesheet" href="<c:url value='/includes/stylesheets/fontawesome/css/font-awesome.min.css'/>">
	
	<!--non-local link http://visjs.org/dist/vis.css-->
  	<link type="text/css" rel="stylesheet" href="<c:url value='/includes/stylesheets/vis.css'/>">
    
    <!-- JavaScript
  	================================================== -->
 	<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.8.0/jquery.min.js"></script>
 	
	<!--non-local link http://visjs.org/dist/vis.js-->
 	<script type="text/javascript" src="<c:url value='/includes/js/vis.js'/>"></script>
 	
	<!--[if lt IE 9]>
	<!--non-local link http://html5shim.googlecode.com/svn/trunk/html5.js-->
	<script src="<c:url value='/includes/js/html5.js'/>"></script>
	<![endif]-->
	
	
	
	<!-- Favicons
	================================================== -->
	<link rel="shortcut icon" href="<c:url value='/includes/images/favicon.ico'/>">

<!--leave open for additional header declarations-->
		
		
		