<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8" %>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>
<%@ taglib prefix="tl" tagdir="/WEB-INF/tags" %>

<tl:pageStartStandard user="${user}" pageTitle="About RMap"/>
	<h1>About RMap</h1>
	<p class="greybox">
		<a href="#what-is-rmap">What is RMap?</a>&nbsp;&nbsp;|&nbsp;&nbsp;
		<a href="#who-can-use">Who can use RMap?</a>&nbsp;&nbsp;|&nbsp;&nbsp;
		<a href="#how-create-disco">How do I create a DiSCO?</a>&nbsp;&nbsp;|&nbsp;&nbsp;
		<a href="#using-ids">Using ORCID IDs, DOIs and other PIDs</a>&nbsp;&nbsp;|&nbsp;&nbsp;
		<a href="#why-duplicates">Why are there duplicates in the visualization?</a>&nbsp;&nbsp;|&nbsp;&nbsp;
		<a href="#funding">Funding</a>&nbsp;&nbsp;|&nbsp;&nbsp;
		<a href="#ieee-discos">IEEE DiSCOs</a>&nbsp;&nbsp;|&nbsp;&nbsp;
		<a href="#additional-info">Additional information</a>
	</p>
	
	<div id="what-is-rmap"></div>
	<h2>What is RMap?</h2>
	
	<p>Today's scholarly works can be dynamic, distributed, and complex. They can consist of multiple related components
	(article, dataset, software, multimedia, webpage, etc.) that are made available asynchronously, assigned a range of identifiers,
	and stored in different repositories. The goal of RMap is to provide a service that allows you to capture and preserve the maps of 
	relationships found amongst these distributed works that is independent of the works themselves. These maps, which we call 
	"Distributed Scholarly Compound Works" (DiSCOs), can be updated to reflect the components of the work as it evolves.  Each 
	version of a DiSCO is assigned an identifier so that it can be cited or shared with others as a representation of the scope of the work 
	at a point in time. While RMap is primarily a linked data API, for improved navigation and discovery, there is also a search function and 
	visual user interface that allows you to interactively navigate DiSCOs and the resources within them. </p>
	<p>The video below offers a short introduction to some of the concepts behind the RMap:
	<div class="containframe">
		<div class="videoframe"><iframe allowfullscreen="" src="https://www.youtube.com/embed/R0xCjScWbJs"></iframe></div>
	</div>
	</p>
	
	<div id="who-can-use"></div>
	<h2>Who can use RMap?</h2>
	<p>Anyone can view RMap data either through the open API, or by navigating the data in the <a href="<c:url value='/home'/>">visual website</a>.
	The policies around writing data to RMap may vary by institution. 
	<!-- start access description --> 
	In this instance of RMap, anyone with a <a href="https://google.com">Google</a>, <a href="https://twitter.com">Twitter</a>, or <a href="https://orcid.org">ORCID</a> account can <a href="<c:url value='/user/login'/>">log in</a> and create keys that provide write access to the RMap API. All data created through the API is immediately available through the public API and visual website.</p>
	<!-- end access description --> 
	
	<div id="how-create-disco"></div>
	<h2>How do I create a DiSCO?</h2>
	<p>Currently, DiSCOs can only be created through the RMap API. 
	<c:if test="${SITEPROPS.isOauthEnabled()}">
	API keys for write access can be generated by logging into this website.
	</c:if>
	Data submitted through the API must be formatted as valid RMap DiSCOs - a simple RDF model that can wrap around most RDF graphs with a few constraints: 
	(1) the DiSCO has two required fields "rdf:type=DiSCO" and a list of "aggregated resources", and (2) the RDF graph must be fully connected to the 
	aggregated resources listed.</p>
	<p>For full documentation on the RMap data model and how to use the API to create DiSCOs please visit the <a href="https://rmap-project.atlassian.net/wiki/spaces/RMAPPS/overview">RMap Technical Wiki</a>. 
	Feel free to <a href="mailto:${SITEPROPS.getContactEmail()}">contact us</a> with any questions about obtaining API keys, or creating DiSCOs.
	</p>
	
	<div id="using-ids"></div>
	<h2>Using ORCID IDs, DOIs, and other PIDs</h2>
	<p>Where possible, it is recommended that the resources expressed in your DiSCOs are represented using unique persistent identifiers (PIDs) such as DOIs, ORCID IDs, 
	ARK IDs, Handles, ISNIs etc. This is not a requirement, all identifier types are accepted provided they are expressed as RDF, but using PIDs in a consistent way 
	allows us to unambiguously connect related works and contributors, improving data quality and discovery.  The RMap technical wiki includes some 
	<a href="https://rmap-project.atlassian.net/wiki/spaces/RMAPPS/pages/198475777/RMap+DiSCO+Best+Practices" target="_blank">best practices</a> for 
	linking and using these various related identifiers in a way that will encourage consistency around identifier use.
	</p>
	<c:if test="${SITEPROPS.isOrcidEnabled()}">
	<p>As an <a href="https://orcid.org/about/what-is-orcid/mission">ORCID</a> member, we are supporting the use of your ORCID account credentials for logging into 
	RMap and creating API keys. This is offered as a convenience for ORCID users but does not currently mean that the DiSCOs you create are automatically linked to 
	your ORCID ID. API users have full control over the content of their DiSCOs, so data creators can, for example, use their ORCID ID in the optional “creator” 
	field of the DiSCO, or as contributor IDs that are connected to scholarly works referenced in your DiSCOs.</p>
	</c:if>
	
	<div id="why-duplicates"></div>
	<h2>Why are there duplicates in the visualizations?</h2>
	<p>The visualizations on this website are a reflection of the raw data in RMap's database. Each item seen in a visualization represents an identifier within 
	the RMap database. Many items can be represented by more than one identifier and each of these will appear visually as a separate entity. Even though these 
	identifiers are referring to the same thing (person, article etc), they might also have different information or relationships associated with them. The 
	user interface does not currently provide a way to condense these into a single view. As an example, a person might have an ORCID ID as well as an identity 
	on a number of other platforms such as Scopus, Facebook, LinkedIn, and others. In the visualization these identities will appear as separate when in fact they 
	all represent the same person. The RMap technical wiki includes some <a href="https://rmap-project.atlassian.net/wiki/spaces/RMAPPS/pages/198475777/RMap+DiSCO+Best+Practices" target="_blank">best practices</a> 
	for linking and using these various related identifiers in a way that will support better discovery and encourage consistency around identifier use.
	</p>
	
	<div id="funding"></div>
	<h2>Funding</h2>
	<p>The original RMap project was funded by the <a href="https://sloan.org/" target="_blank">Alfred P. Sloan Foundation</a> and undertaken by the 
	<a href="http://dataconservancy.org/" target="_blank">Data Conservancy</a>, <a href="https://www.portico.org/" target="_blank">Portico</a>, 
	and <a href="https://www.ieee.org" target="_blank">IEEE</a>. 
	This instance of RMap is managed by 
	<a href="${SITEPROPS.getInstitutionUrl()}" target="_blank">${SITEPROPS.getInstitutionName()}</a>.
	</p>
			
	<div id="ieee-discos"></div>
	<h2>IEEE DiSCOs</h2>
	<p>The <a href="https://rmap-hub.org">instance of RMap</a> hosted by the <a href="https://library.jhu.edu/" target="_blank">Sheridan Libraries at Johns Hopkins University</a> was 
	initially populated using over 680,000 DiSCOs provided by the <a href="https://www.ieee.org" target="_blank">Institute of Electrical and Electronics Engineers</a> (IEEE). 
	These were created using IEEE’s article database. All of them include basic article metadata such as title, journal, and author names, but many also contain additional relationships 
	such as citation links, ORCID IDs, and dataset links as available.</p>
		
	<div id="additional-info"></div>
	<h2>Additional information</h2>
	<p>For additional information about RMap, visit the <a href="http://rmap-project.info/rmap/?page_id=98" target="_blank">RMap Project website</a>. 
	To view the RMap code, report bugs, or request changes, visit the <a href="https://github.com/rmap-project/rmap" target="_blank">RMap GitHub project</a>. 
	To read about technical detail of RMap including API instructions, visit the <a href="https://rmap-project.atlassian.net/wiki/spaces/RMAPPS/overview" target="_blank">RMap Techncial Wiki</a>. 
	For all other questions, please contact us at <a href="mailto:${SITEPROPS.getContactEmail()}">${SITEPROPS.getContactEmail()}</a></p>
	<br/>
<tl:pageEndStandard/>
