<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="my" uri="/WEB-INF/tld/rmapTagLibrary.tld" %>
<%@ taglib prefix="tl" tagdir="/WEB-INF/tags" %>


<c:set var="disco_graph_triples_offset" value="${empty param.gt_offset? 0 : param.gt_offset}"/>
<c:set var="disco_table_triples_offset" value="${empty param.tt_offset? 0 : param.tt_offset}"/>

<tl:pageStartGraph pageTitle="RMap DiSCO" user="${user}" viewMode="standard" pageType="disco"
					resourceUri="${RESOURCEURI.toString()}"/>
        
	<article class="twelve columns main-content">
		
		<tl:tabsGraphTable/>
		
		<h1>RMap DiSCO</h1>
		<h2>URI: ${DISCO.getUri()}</h2>
		<p>
			<c:if test="${DISCO.getCreator().length()>0}">
				<strong>Created by:</strong> <tl:linkRMapValue uri="${DISCO.getCreator()}"/><br/>
			</c:if>
			<c:if test="${DISCO.getProvGeneratedBy().length()>0}">
				<strong>Generated by:</strong> <tl:linkRMapValue uri="${DISCO.getProvGeneratedBy()}"/><br/>
			</c:if>
			<c:if test="${DISCO.getDescription().length()>0}">
				<strong>Description:</strong> ${DISCO.getDescription()}<br/>
			</c:if>
		</p>
		
		<div id="graphview" class="tabcontent" data-offset="${disco_graph_triples_offset}">
			<tl:loadingIcon/>
		</div>
		
		<div id="tableview" class="tabcontent" data-offset="${disco_table_triples_offset}">
			<tl:loadingIcon/>
		</div>
	</article>
	
	<!-- End main Content -->
		    
	<aside class="four columns right-sidebar">
	     
		<div class="sidebar-widget">
			<div class="status${DISCO.getStatus().toString()}"><h1>${DISCO.getStatus().toString()}</h1></div>
			<h2>Related Events</h2>
			<ul>
				<c:forEach var="event" items="${DISCO.getEvents()}">
					<li><tl:linkRMapInternal type="event" uri="${event.toString()}"/></li>
				</c:forEach>
			</ul>
			
			<c:set var="agentVersions" value="${DISCO.getAgentVersions()}"/>
			<h2>Other DiSCO Versions</h2>
			<h3>Same agent</h3>
			<c:if test="${agentVersions!=null && agentVersions.size()>0}">
				<ul>
				<c:forEach var="version" items="${agentVersions}">
					<li><tl:linkRMapInternal type="disco" uri="${version.toString()}"/></li>
				</c:forEach>
				</ul>
			</c:if>
			<c:if test="${agentVersions==null || agentVersions.size()==0}">
				<p><em>None found</em></p>
			</c:if>
	
			<c:set var="otherAgentVersions" value="${DISCO.getOtherAgentVersions()}"/>
			<h3>Other agents</h3>
			<c:if test="${otherAgentVersions!=null && otherAgentVersions.size()>0}">
				<ul>
				<c:forEach var="version" items="${otherAgentVersions}">
					<li><tl:linkRMapInternal uri="${version.toString()}" type="disco"/></li>
				</c:forEach>
				</ul>
			</c:if>
			<c:if test="${otherAgentVersions==null || otherAgentVersions.size()==0}">
				<p><em>None found</em></p>
			</c:if>
		</div>
	</aside>
	<!-- End Right Sidebar -->


<tl:pageEndStandard/>